create table if not exists public.applications (
  id bigint generated by default as identity primary key,
  player_name text not null,
  pubg_id text not null,
  discord text default '',
  device text default '',
  fps text default '',
  role text default '',
  description text default '',
  video_url text not null,
  created_at timestamptz default now()
);

alter table public.applications enable row level security;

drop policy if exists "applications public insert" on public.applications;
drop policy if exists "applications public read" on public.applications;

create policy "applications public insert"
on public.applications
for insert
with check (true);

create policy "applications public read"
on public.applications
for select
using (true);
